# Generated by Django 4.2.7 on 2025-04-08 00:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('close_date', models.DateField()),
                ('probability', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('next_step', models.CharField(blank=True, max_length=255, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_won', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='contacts.account')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_opportunities', to='accounts.user')),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
            },
        ),
        migrations.CreateModel(
            name='PriceBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('standard_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('probability', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_won', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.opportunity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product')),
            ],
            options={
                'unique_together': {('opportunity', 'product')},
            },
        ),
        migrations.CreateModel(
            name='OpportunityContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.opportunity')),
            ],
            options={
                'unique_together': {('opportunity', 'contact')},
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='contacts',
            field=models.ManyToManyField(related_name='opportunities', through='sales.OpportunityContact', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='products',
            field=models.ManyToManyField(related_name='opportunities', through='sales.OpportunityProduct', to='sales.product'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='sales.salesstage'),
        ),
        migrations.CreateModel(
            name='PriceBookEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('price_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='sales.pricebook')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_book_entries', to='sales.product')),
            ],
            options={
                'unique_together': {('price_book', 'product')},
            },
        ),
    ]
